pipeline {
    agent any
    environment {
        IMAGE_NAME = "gitops-app"
    }
    stages {
        stage('Validation') {
            steps {
                echo "Validating Dockerfile syntax..."
                sh "docker version" 
            }
        }
        stage('Build & Deploy') {
            steps {
                script {
                    if (env.BRANCH_NAME == 'main') {
                        echo "--- DEPLOYING TO DEV ---"
                        sh "sudo docker build --build-arg ENV_TYPE=Development -t ${IMAGE_NAME}:dev ."
                        sh "sudo docker rm -f dev-container || true"
                        sh "sudo docker run -d --name dev-container -p 8081:80 ${IMAGE_NAME}:dev"
                    } 
                    else if (env.BRANCH_NAME == 'branch1') {
                        echo "--- DEPLOYING TO BRANCH1 ---"
                        sh "sudo docker build --build-arg ENV_TYPE=Production -t ${IMAGE_NAME}:prod ."
                        sh "sudo docker rm -f prod-container || true"
                        sh "sudo docker run -d --name prod-container -p 8082:80 ${IMAGE_NAME}:prod"
                    }
                }
            }
        }
    }
}